POST http://localhost:5191/breakfasts
Content-Type: application/json

{
    "name": "Noodles Sushi",
    "description": "Noodles sushi with tasty flavor!",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2024-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}

###
http://localhost:5191/Breakfasts/4C4BC740-1C38-40FC-9152-CB3C2C1DA36F