@id = 4c4bc740-1c38-40fc-9152-cb3c2c1da36f

PUT http://localhost:5191/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Noodles Sushi 2",
    "description": "Noodles sushi with tasty flavor!",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2024-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}